package RennegadeGUI;

import java.awt.*;
import java.io.*;
import java.util.*;

/**
 * 
 * @author LukeHarper 1092144
 * @version PDC Assignment 2014 Semester 1
 */
public class Menu extends javax.swing.JFrame {

    private String playerAccount;

    /**
     * Sets the Menu GUI dimensions and visibility
     */
    public Menu() {
        
        initComponents();
        //Set Location Centre
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        createnew.setVisible(false);
        existing.setVisible(false);
        main.setVisible(false);
    }

    /**
     * Get the account of the player
     * @return the account
     */
    public String getAccount() {
        return playerAccount;
    }

    /**
     * Resets GUI fields to default values
     */
    public void resetFields() {
        password.setText("");
        account.setText("");
        character.setText("");
        vocation.setSelectedIndex(0);
        existingpass.setText("");
        existingacc.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd = new javax.swing.JLabel();
        options = new javax.swing.JPanel();
        main = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        newgame = new javax.swing.JButton();
        createnew = new javax.swing.JPanel();
        create = new javax.swing.JButton();
        cname = new javax.swing.JLabel();
        account2 = new javax.swing.JLabel();
        password2 = new javax.swing.JLabel();
        vocation = new javax.swing.JComboBox();
        character = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        account = new javax.swing.JTextField();
        existing = new javax.swing.JPanel();
        login2 = new javax.swing.JButton();
        account3 = new javax.swing.JLabel();
        password3 = new javax.swing.JLabel();
        existingacc = new javax.swing.JTextField();
        existingpass = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rennegade RPG");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 475));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(cmd);
        cmd.setBounds(10, 0, 790, 30);

        options.setOpaque(false);
        options.setLayout(null);

        main.setText("Main Menu");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });
        options.add(main);
        main.setBounds(10, 20, 130, 24);

        exit.setText("Exit Game");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        options.add(exit);
        exit.setBounds(10, 60, 130, 24);

        getContentPane().add(options);
        options.setBounds(630, 350, 150, 100);

        menu.setOpaque(false);
        menu.setLayout(null);

        login.setText("Login ");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        menu.add(login);
        login.setBounds(10, 20, 130, 24);

        newgame.setText("Start New Game");
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });
        menu.add(newgame);
        newgame.setBounds(10, 70, 130, 24);

        getContentPane().add(menu);
        menu.setBounds(320, 190, 150, 120);

        createnew.setOpaque(false);
        createnew.setLayout(null);

        create.setText("Create Account");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        createnew.add(create);
        create.setBounds(100, 190, 130, 24);

        cname.setText("Character Name:");
        createnew.add(cname);
        cname.setBounds(20, 50, 130, 30);

        account2.setText("Account Name:");
        createnew.add(account2);
        account2.setBounds(20, 90, 120, 30);

        password2.setText("Account Password:");
        createnew.add(password2);
        password2.setBounds(20, 130, 130, 30);

        vocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sorcerer", "Knight", "Paladin" }));
        createnew.add(vocation);
        vocation.setBounds(90, 10, 150, 23);
        createnew.add(character);
        character.setBounds(140, 50, 170, 30);
        createnew.add(password);
        password.setBounds(140, 130, 170, 30);
        createnew.add(account);
        account.setBounds(140, 90, 170, 30);

        getContentPane().add(createnew);
        createnew.setBounds(230, 150, 350, 230);

        existing.setOpaque(false);
        existing.setLayout(null);

        login2.setText("Login ");
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });
        existing.add(login2);
        login2.setBounds(100, 110, 130, 24);

        account3.setText("Account Name:");
        existing.add(account3);
        account3.setBounds(20, 20, 120, 30);

        password3.setText("Account Password:");
        existing.add(password3);
        password3.setBounds(20, 60, 130, 30);
        existing.add(existingacc);
        existingacc.setBounds(140, 20, 170, 30);
        existing.add(existingpass);
        existingpass.setBounds(140, 60, 170, 30);

        getContentPane().add(existing);
        existing.setBounds(230, 180, 320, 150);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RennegadeGUI/game_background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -20, 800, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // Sets panel visibility
        menu.setVisible(false);
        createnew.setVisible(true);
        main.setVisible(true);
    }//GEN-LAST:event_newgameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // Sets panel visibility
        menu.setVisible(false);
        existing.setVisible(true);
        main.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // Exits the game
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        // Check if account login in details are valid && log in if successful
        String accInput = existingacc.getText();
        String passInput = existingpass.getText();
        boolean success = false;
        // Account & Password incorrect
        try {
            Scanner input = new Scanner(new File(accInput + ".txt"));
            if (!passInput.equals(input.nextLine())) {
                cmd.setText("Account or Password is incorrect. Please Try again..");
            } else {
                success = true;
            }
        } catch (FileNotFoundException e) {
            cmd.setText("Account or Password is incorrect. Please Try again..");
        }
        // Account login successful
        if (success) {
            playerAccount = accInput;
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
            this.setVisible(false);
        }
    }//GEN-LAST:event_login2ActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // Setup Character
        String charInput = character.getText();
        String accInput = account.getText();
        String passInput = password.getText();
        int voc = vocation.getSelectedIndex();
        boolean success = false;
        // Account creation validation
        if (accInput.length() < 4 || passInput.length() < 4) {
            cmd.setText("Your Account Name and Password must be atleast 4 characters");
        } else {
            if (accInput.length() <= 8) {
                if (passInput.length() <= 8) {
                    try {
                        Scanner input = new Scanner(new File(accInput + ".txt"));
                        cmd.setText("There is already an account with that name, Try again.");
                    } catch (FileNotFoundException e) {
                        success = true;
                    }
                    if (success) {
                        // Account created, set up character database
                        try {
                            BufferedWriter out = new BufferedWriter(new FileWriter(accInput + ".txt"));
                            out.write(passInput + "\n");
                            out.write(charInput + "\n");
                            out.write(voc + "\n");
                            out.write("1" + "\n");
                            out.write("0" + "\n");
                            int weapon = 0;
                            if (voc == 0) {
                                weapon = 12;
                            }
                            if (voc == 2) {
                                weapon = 6;
                            }
                            out.write(weapon + "\n");
                            out.close();
                            cmd.setText("Account successfully created.");
                        } catch (IOException e) {
                        }
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            Thread.currentThread().interrupt();
                        }
                        // Sets panel visibility
                        cmd.setText("Account successfully created.");
                        createnew.setVisible(false);
                        main.setVisible(false);
                        menu.setVisible(true);
                        resetFields();

                    }
                } else {
                    cmd.setText("Account password cannot exceed 8 characters");
                }
            } else {
                cmd.setText("Account name cannot exceed 8 characters");
            }
        }
    }//GEN-LAST:event_createActionPerformed

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        // Sets panel visibility
        menu.setVisible(true);
        createnew.setVisible(false);
        existing.setVisible(false);
        main.setVisible(false);
        resetFields();
    }//GEN-LAST:event_mainActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account;
    private javax.swing.JLabel account2;
    private javax.swing.JLabel account3;
    private javax.swing.JLabel background;
    private javax.swing.JTextField character;
    private javax.swing.JLabel cmd;
    private javax.swing.JLabel cname;
    private javax.swing.JButton create;
    private javax.swing.JPanel createnew;
    private javax.swing.JPanel existing;
    private javax.swing.JTextField existingacc;
    private javax.swing.JPasswordField existingpass;
    private javax.swing.JButton exit;
    private javax.swing.JButton login;
    private javax.swing.JButton login2;
    private javax.swing.JButton main;
    private javax.swing.JPanel menu;
    private javax.swing.JButton newgame;
    private javax.swing.JPanel options;
    private javax.swing.JTextField password;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel password3;
    private javax.swing.JComboBox vocation;
    // End of variables declaration//GEN-END:variables

}
